### ISSUE TITLE
ViewInjector only generates method from the first interface super class

### ISSUE THREAD

**Issue by CarlosMChica** [PaNaVTEC/ViewThreadDecorator#4] opened 2015-11-27 15:48 UTC

**Comment by CarlosMChica** [comment] 2015-11-27 15:52
It does work if the annotated @ThreadViewDecorated interface es de highest interface in the hierarchy

**Comment by CarlosMChica** [comment] 2015-11-27 16:05
if an interface extends more than one interface then the generated decorated class should implement all interfaces.

**Comment by PaNaVTEC** [comment] 2015-12-01 11:53
So, for readers, the problem is if you have a view interface hierarchy with more than 2 parents. It will be fixed in the next release.

**Comment by PaNaVTEC** [comment] 2015-12-07 09:20
Fixed in 1.5.2

**Closed as completed by PaNaVTEC** 2015-12-07 09:20 UTC
